name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Or your preferred Node.js version

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 # Or your preferred pnpm version
          # Defaults to true, but explicit is better
          cache-dependency-path: "package.json"

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: List files in workspace root
        run: ls -l ./

      - name: List files in ./public directory
        run: ls -l ./public #  <-- Assuming ./public is a likely output directory

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./src #  <-- Adjust this based on 'ls -l' output if needed
          force: true
