name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your main branch name (e.g., master)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Or your preferred Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src # Or the directory where your build output is located (e.g., dist, public)
          force: true # Optional: Force push changes
